### ISSUE TITLE
 raise IOError( OSError: MoviePy error: failed to read the duration of file 

### ISSUE THREAD

**Issue by metapodcod** [aaqibmehrban/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader#1]
trying link  https://www.reddit.com/r/Turkey/comments/igyqs6/bazen_bir_bakış_bir_ülkeyi_anlatır_namussuz_sapık/  (turkish lang)

```
python run.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Directory Generated : generated  Created 
Directory Generated : voices  Created    
Video Started
thinkingme

-----------start
[['Bazen bir bakış bir ülkeyi anlatır. Namussuz sapık Musa Orhan tutuklanmalı.']]
----------------
now going to draw:
['Bazen bir bakış bir ülkeyi anlatır. Namussuz sapık Musa Orhan tutuklanmalı.']
now going to draw:
now going to draw:
*********draw:  0.11887693405151367
['Kızı intihar ettiği için ağlıyor, tecavüz edildiği için değil\n\n \n\nDavada evlenme', 'vaadiyle kandırıldığı geçiyor. Dava sonuçlanmadan 
insanları linç etmeye ne', 'meraklısınız, tecavüzcüyse allah belasını versin ama ya değilse bu ettiğiniz', 'laflar ne olacak']
------------end=---------
[['Bazen bir bakış bir ülkeyi anlatır. Namussuz sapık Musa Orhan tutuklanmalı.']]
-------------------------
 Bazen bir bakış bir ülkeyi anlatır. Namussuz sapık Musa Orhan tutuklanmalı.
 
 Kızın yazdığı mektup ne peki!? İftira edip sonra da intihar mı etmiş? Daha önce de yaptım bana kimse hesap soramaz dememiş mi yani?!
*********chat:  12.646354675292969
*********pause:  0.0
combine function
[['Bazen bir bakış bir ülkeyi anlatır. Namussuz sapık Musa Orhan tutuklanmalı.']]
this is the making video :0
this is the making video :0
Traceback (most recent call last):
  File "C:\Users\metapod\Desktop\python\reddit\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 318, in ffmpeg_parse_infos
    match = re.findall("([0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9])", line)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 335, in <module>
    get_script()
  File "run.py", line 257, in get_script
    makingVideo(comments, post_titles,post_bodies)
  File "C:\Users\metapod\Desktop\python\reddit\makingVideo.py", line 25, in makingVideo
    audio = AudioFileClip(r'{}\voices\part97'.format(folder_path) + '-' + str(i) + '.mp3')
  File "C:\Users\metapod\Desktop\python\reddit\venv\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 71, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "C:\Users\metapod\Desktop\python\reddit\venv\lib\site-packages\moviepy\audio\io\readers.py", line 50, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "C:\Users\metapod\Desktop\python\reddit\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 321, in ffmpeg_parse_infos     
    raise IOError(
OSError: MoviePy error: failed to read the duration of file C:\Users\metapod\Desktop\python\reddit\voices\part97-0.mp3.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[wav @ 043e5480] Cannot check for SPDIF
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'C:\Users\metapod\Desktop\python\reddit\voices\part97-0.mp3':
  Duration: N/A, bitrate: 352 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, mono, s16, 352 kb/s
At least one output file must be specified
```

In some links, it just takes the names of the authors and waits for a long time .. for example in this link (I waited exactly 4 hours :)))
https://www.reddit.com/r/Turkey/comments/igx26t/diyanet_başkanı_yaptığı_bu_açıklamayla_tepki_bile/ 

@aaqibmehrban

**Comment by 0xBabatunde** [comment]
I'm getting the same issue as above.

**Comment by aaqibmehrban** [comment]
Yes actually this problem is in the praw library.
The API of Reddit.
It is unable to return comments. and author name. for some links

maybe due to the privacy or anything else.

Alternate for this will be to use any other scraping method.
to avoid this issue.
