### ISSUE TITLE
Doesn't work on other environements

### ISSUE THREAD

**Issue by JDuggal760** [aaqibmehrban/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader#3]
When I tried this bot on windows, Linux, and kali I got errors on all 3. On windows it was a failed to create process(windows 10 64 bit, python 3.9.1). Linux was could not find specified file while I was in directory. Kali had issue with python. Should I try using the windows 10 python 3.7.4 environment to see if that works?

**Comment by bilalmehrban** [comment]
@aaqibmehrban

**Comment by aaqibmehrban** [comment]
> When I tried this bot on windows, Linux, and kali I got errors on all 3. On windows it was a failed to create process(windows 10 64 bit, python 3.9.1). Linux was could not find specified file while I was in directory. Kali had issue with python. Should I try using the windows 10 python 3.7.4 environment to see if that works?

can you share exactly where you getting the issue and when?
do share screenshot.

**Comment by alphanumericaltycoon** [comment]
Hi there,

I ran the script too on Kali Linux and followed the installation steps but appear to be having some problems. Below is my terminal output:

```

┌──(kali㉿kali)-[~/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader]
└─$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting absl-py==0.9.0
  Downloading absl-py-0.9.0.tar.gz (104 kB)
     |████████████████████████████████| 104 kB 3.4 MB/s 
Collecting Adyen==2.2.0
  Downloading Adyen-2.2.0.tar.gz (12 kB)
Requirement already satisfied: aiodns==2.0.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.0.0)
Collecting aiohttp==3.6.2
  Downloading aiohttp-3.6.2-py3-none-any.whl (441 kB)
     |████████████████████████████████| 441 kB 33.7 MB/s 
Collecting aiohttp-socks==0.4.1
  Downloading aiohttp_socks-0.4.1-py3-none-any.whl (17 kB)
Collecting alembic==1.3.2
  Downloading alembic-1.3.2.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 4.3 MB/s 
Collecting altgraph==0.16.1
  Downloading altgraph-0.16.1-py2.py3-none-any.whl (20 kB)
Collecting anticaptchaofficial==1.0.23
  Downloading anticaptchaofficial-1.0.23-py3-none-any.whl (8.4 kB)
Collecting app==0.0.1
  Downloading app-0.0.1.zip (2.2 kB)
Collecting appdirs==1.4.3
  Downloading appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting arabic-reshaper==2.1.0
  Downloading arabic_reshaper-2.1.0.tar.gz (18 kB)
Collecting asgiref==3.2.3
  Downloading asgiref-3.2.3-py2.py3-none-any.whl (18 kB)
Collecting asn1crypto==0.24.0
  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)
     |████████████████████████████████| 101 kB 3.6 MB/s 
Collecting astor==0.8.1
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Requirement already satisfied: async-timeout==3.0.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 15)) (3.0.1)
Collecting atomicwrites==1.3.0
  Downloading atomicwrites-1.3.0-py2.py3-none-any.whl (5.9 kB)
Collecting attrs==19.3.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting auto-py-to-exe==2.6.5
  Downloading auto_py_to_exe-2.6.5-py2.py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 2.7 MB/s 
Collecting Automat==0.8.0
  Downloading Automat-0.8.0-py2.py3-none-any.whl (31 kB)
Collecting backcall==0.1.0
  Downloading backcall-0.1.0.zip (11 kB)
Collecting beautifulsoup4==4.8.2
  Downloading beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 5.1 MB/s 
Collecting bleach==3.1.0
  Downloading bleach-3.1.0-py2.py3-none-any.whl (157 kB)
     |████████████████████████████████| 157 kB 4.6 MB/s 
Collecting bottle==0.12.17
  Downloading bottle-0.12.17-py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 3.6 MB/s 
Collecting bottle-websocket==0.2.9
  Downloading bottle-websocket-0.2.9.tar.gz (2.0 kB)
Collecting browser-cookie3==0.11.1
  Downloading browser-cookie3-0.11.1.tar.gz (7.6 kB)
Collecting browsercookie==0.7.6
  Downloading browsercookie-0.7.6.tar.gz (6.0 kB)
Requirement already satisfied: bs4==0.0.1 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 27)) (0.0.1)
ERROR: Could not find a version that satisfies the requirement build==1.0.2 (from versions: 0.0.1, 0.0.2, 0.0.3.1, 0.0.4, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.1.post1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1)                                
ERROR: No matching distribution found for build==1.0.2
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader]
└─$ python3 run.py                                                                                                1 ⨯
Traceback (most recent call last):
  File "/home/kali/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader/run.py", line 3, in <module>
    import pyttsx3
ModuleNotFoundError: No module named 'pyttsx3'
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader]
└─$ pip install pyttsx3                                                                                           1 ⨯
Defaulting to user installation because normal site-packages is not writeable
Collecting pyttsx3
  Downloading pyttsx3-2.90-py3-none-any.whl (39 kB)
Installing collected packages: pyttsx3
Successfully installed pyttsx3-2.90
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader]
└─$ python3 run.py     
Traceback (most recent call last):
  File "/home/kali/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader/run.py", line 4, in <module>
    import comtypes.client
ModuleNotFoundError: No module named 'comtypes'
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader]
└─$ pip install comtypes                                                                                          1 ⨯
Defaulting to user installation because normal site-packages is not writeable
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f04745d1b80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/comtypes/                                    
Collecting comtypes
  Downloading comtypes-1.1.10.tar.gz (145 kB)
     |████████████████████████████████| 145 kB 2.7 MB/s 
Building wheels for collected packages: comtypes
  Building wheel for comtypes (setup.py) ... done
  Created wheel for comtypes: filename=comtypes-1.1.10-py3-none-any.whl size=164937 sha256=05d961dc35183d203639a1f1a892698a1a3290c4f031ee73c84c1d3d62e45e82
  Stored in directory: /home/kali/.cache/pip/wheels/76/c4/bb/651111ab6c5e31ad6a1ff3022bfdbef5a4e88bfe568150870c
Successfully built comtypes
Installing collected packages: comtypes
Successfully installed comtypes-1.1.10
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader]
└─$ python3 run.py      
Traceback (most recent call last):
  File "/home/kali/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader/run.py", line 4, in <module>
    import comtypes.client
  File "/home/kali/.local/lib/python3.9/site-packages/comtypes/__init__.py", line 23, in <module>
    from _ctypes import COMError
ImportError: cannot import name 'COMError' from '_ctypes' (/usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so)
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader]
└─$ python3 run.py                                                                                                1 ⨯
Traceback (most recent call last):
  File "/home/kali/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader/run.py", line 4, in <module>
    import comtypes.client
  File "/home/kali/.local/lib/python3.9/site-packages/comtypes/__init__.py", line 23, in <module>
    from _ctypes import COMError
ImportError: cannot import name 'COMError' from '_ctypes' (/usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so)
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader]
└─$    
```

Would be grateful for any advice on how to get this up and running.
