### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by N0THSA** [aaqibmehrban/MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader#4]
C:\Users\Ashton\Desktop\MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader-master>py run.py
Directory Generated : generated  Created
Directory Generated : voices  Created
Video Started
Traceback (most recent call last):
  File "C:\Users\Ashton\Desktop\MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader-master\run.py", line 335, in <module>
    get_script()
  File "C:\Users\Ashton\Desktop\MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader-master\run.py", line 54, in get_script
    title_for_thumbnail,post_bodies,post_bod_y_locations,replies_author,replies,replies_y_locations) = new_scrapr(urls, total_cmnts)
  File "C:\Users\Ashton\Desktop\MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader-master\reddit_scrapper_new.py", line 9, in new_scrapr
    c_id = file[0].split(':')[1].strip()
IndexError: list index out of range

C:\Users\Ashton\Desktop\MASCALOGICS-Automatic-Reddit-text-to-Video-Generator-and-youtube-uploader-master>

**Comment by aaqibmehrban** [comment]
Added credentials.txt file just put relevant information of praw api and run again.
it will work.
